### ISSUE TITLE
Problem while transmitting SMS to Nokia 3720c

### ISSUE THREAD

**Issue by Olfried2** [gammu/wammu#15]
while trying to sen a sms, I got the attached errormessage.
Hope this helps
![wammu_unhandled exception_001](https://cloud.githubusercontent.com/assets/3833312/10284396/21b348a2-6b84-11e5-98a3-7dc3418ee95c.png)

**Comment by nijel** [comment]
Can you please include the debug log? Or at least Gammu and Wammu versions... Also it's quite likely that the bug has been fixed in newer versions.

**Comment by Olfried2** [comment]
Oh, sorry. I just installed it via apt-get and thought I got the actual version. FYI  Gammu 1.33.0 Wammu 0.36 python-gammu 1.33.0  after sending this I'll look for a newer version. Thanks for your support.

**Comment by nijel** [comment]
Some newer packages are here: https://launchpad.net/~nijel/+archive/ubuntu/ppa
