### ISSUE TITLE
Wrong +CREG command for Motorola Razr V3

### ISSUE THREAD

**Issue by b64** [gammu/wammu#16]
1. The Motorola Razr V3 must be in Mode=0 when it receives the CREG=n command.
Reference: http://read.pudn.com/downloads139/doc/599044/AT_Commands_Ref.pdf
2. The Motorola Razr V3 accepts only a value of n=(0,1), not (0-2).  
Reference: The phone responds: AT+CREG=?
+CREG: (0-1)  !NOT (0-2)!
a) Function GSM_Error ATGEN_GetNetworkInfo() sends "AT+CREG=2" instead of "AT+CREG=1" (at least for a Razr V3, wrong command parameter).  AT+CREG=2 causes an ERROR reply from the phone.
b) The expected Razr V3 phone response for a AT+CREG=1 command  is OK; however, gammu checks and complains about a CREG=1 / OK response.
```
Wed 2015/11/04 08:08:09: [Model name: `V3']
Wed 2015/11/04 08:08:09: [Model data: `V3 Razr']
Wed 2015/11/04 08:08:09: [Model data: `V3']
Wed 2015/11/04 08:08:09: [Connected model  - "V3"]
Wed 2015/11/04 08:08:10: 1 "AT+CGMI"
Wed 2015/11/04 08:08:10: 2 "+CGMI: "Motorola CE, Copyright 2004""
```

**Comment by nijel** [comment]
The CREG=1/2 issue should be already fixed by https://github.com/gammu/gammu/issues/142.

The mode should be already set to 0 according to current code.

**Comment by b64** [comment]
On Wednesday, November 04, 2015 01:12:00 AM Michal Čihař wrote:
> The CREG=1/2 issue should be already fixed by
> https://github.com/gammu/gammu/issues/142.
> 
> The mode should be already set to 0 according to current code.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gammu/wammu/issues/16#issuecomment-153647627

Hi Michal,

Thank you for your prompt answer!

First apologies for my error in the description.  The Motorola Razr V3 must be in 
Mode=2 when it executes the command AT+CREG=<n>.  This requires a modification 
in motorola.c in the MOTOROLA_CommandInfo Commands[] array 
to make the +CREG command a Mode2 command.  My patch is in the attached file 
motorola.c.patch
Note: This modification will probably affect other Motorola devices as well. 

FYI:  From the Motorola manual "AT Commands Reference for Motorola Handsets. 
Motorola OS 3G-GSM": 
"Set command controls the presentation of an unsolicited result code +CREG: <stat> 
when <n>=1 and there is a change in the Mobile Equipment network registration 
status, or code +CREG: <stat>[,<lac>,<ci>] when <n>=2 and there is a change of 
the network cell. (..)"
"NOTE: Make sure that command is running from Accessories Mode +MODE = 2. P2K 
phones default to +MODE = 0 on power-up. (..) 
This command is supported on platforms that have feature 8194 or 13816 enabled. 
(..) *Feature 8194 and 13816 do not support <n>=2* or <stat>=3."

Second, contrary to what you stated, the change for AT+CREG=1 which you 
mentioned has !NOT! made its way into the source code gammu-1.36.6; i.e. the 
problem has NOT been fixed in this version. 
I had already patched my code in atgen.c starting at line 3131 with two if-statements.  
With this patch I send AT+CREG=1 to a Motorola Razr V3 but send AT+CREG=2 to all 
other phones/modems.  However, gammu checked the phone response of an 
AT+CREG=1 command and complained, although it looked good.  There I got stuck 
and opened the ticket.  

For your convenience, my patch is in atgen.c.patch.  It also includes two ADDED lines 
in the GSM_Reply_Function ATGENReplyFunctions[] array
as per matahr's description in that previous issue "GSM_GetNetworkInfo failed with 
error UNKNOWN" which you referenced:  
Line 5972: Added{ATGEN_GenericReply, "AT+CREG=1" 
,0x00,0x00,ID_ConfigureNetworkInfo },{ATGEN_GenericReply, "AT+CGREG=1" 
,0x00,0x00,ID_ConfigureNetworkInfo },

matahr mentioned in this previous issue that the above two lines have to be ADDED in 
atgen.c for the Motorola Razr  V3  around line number 5972.  I am curious about the 
use of the word 'added'.  Does this mean that with this addition there are now two 
entries 
{ATGEN_GenericReply,   "AT+CREG=1"  ,0x00,0x00,ID_ConfigureNetworkInfo  },
{ATGEN_GenericReply,   "AT+CGREG=1" ,0x00,0x00,ID_ConfigureNetworkInfo },
and at the same time also 
{ATGEN_GenericReply,   "AT+CREG=2" ,0x00,0x00,ID_ConfigureNetworkInfo    },
{ATGEN_GenericReply,   "AT+CGREG=2" ,0x00,0x00,ID_ConfigureNetworkInfo  },
in this array?  Does this not cause a conflict?

If my understanding is wrong, can you think of a way to provide dual functionality in 
gammu for a Motorola Razr V3  - AND - for other phones in a similar way like I started 
it?

Greetings, Martin

**Comment by nijel** [comment]
I can not see your patch, probably the email gateway of GitHub doesn't handle attachments...

Anyway the CREG=1 support has been already added in https://github.com/gammu/gammu/commit/8157ed234429a825d335642d8091e2bdc791d2ba

**Comment by b64** [comment]
On Thursday, November 05, 2015 06:05:28 AM Michal Čihař wrote:
> I can not see your patch, probably the email gateway of GitHub doesn't
> handle attachments...
> 
> Anyway the CREG=1 support has been already added in
> https://github.com/gammu/gammu/commit/8157ed234429a825d335642d8091e2bdc791d
> 2ba
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gammu/wammu/issues/16#issuecomment-154066028


Here is the motorola.c patch:

--- orig.motorola.c	2015-11-04 16:16:26.546012979 +0000
+++ motorola.c	2015-11-04 16:16:58.025985291 +0000
@@ -79,11 +79,11 @@
 	{"+CRTT", 2},
 	{"+CMEE", 2},
 	{"+CKPD", 2},
+	{"+CREG", 2},
 
 	{"+CHV", 0},
 	{"+CDV", 0},
 	{"+CPAS", 0},
-	{"+CREG", 0},
 	{"+CSQ", 0},
 	{"+GCAP", 0},
 	{"+CMUT", 0},

And here is the atgen.c patch:

--- orig.atgen.c	2015-11-04 15:24:19.613896247 +0000
+++ atgen.c	2015-11-04 16:03:01.326592807 +0000
@@ -3128,7 +3128,16 @@
 	netinfo->NetworkCode[0] = 0;
 	netinfo->GPRS = 0;
 
-	smprintf(s, "Enable full network info\n");
+	// Motorola Razr V3:
+	//   AT+CREG must be executed in MODE=2 (modified entry in array in 
motorola.c)
+	//   AT+CREG=? (0,1)  !not (0-2)!
+	if ( 0 == strncmp( "V3", s->Phone.Data.Model,2 )) {
+	  smprintf(s, "Motorola V3 network info\n");
+	  error = ATGEN_WaitForAutoLen(s, "AT+CREG=1\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
+	} else {
+	  smprintf(s, "Enable full network info\n");
+	  error = ATGEN_WaitForAutoLen(s, "AT+CREG=2\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
+	} // endif Motorola Razr V3 
 	error = ATGEN_WaitForAutoLen(s, "AT+CREG=2\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
 
 	if ((error != ERR_NONE) &&
@@ -3138,7 +3147,12 @@
 	}
 
 	smprintf(s, "Enable full packet network info\n");
-	error = ATGEN_WaitForAutoLen(s, "AT+CGREG=2\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
+	// Different handling for Motorola Razr V3
+	if ( 0 == strncmp( "V3", s->Phone.Data.Model,2 )) {
+          error = ATGEN_WaitForAutoLen(s, "AT+CGREG=1\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
+	} else {
+	  error = ATGEN_WaitForAutoLen(s, "AT+CGREG=2\r", 0x00, 40, 
ID_ConfigureNetworkInfo);
+	}
 	if (error != ERR_NONE) {
 		return error;
 	}
@@ -5969,6 +5983,8 @@
 {ATGEN_ReplyGetNetworkLAC_CID,	"AT+CREG?"		
,0x00,0x00,ID_GetNetworkInfo	 },
 {ATGEN_ReplyGetPacketNetworkLAC_CID,	"AT+CGREG?"		
,0x00,0x00,ID_GetNetworkInfo	 },
 {ATGEN_ReplyGetGPRSState,	"AT+CGATT?"		,0x00,0x00,ID_GetGPRSState	 
},
+{ATGEN_GenericReply,		"AT+CREG=1"		,0x00,0x00,ID_ConfigureNetworkInfo	
 },
+{ATGEN_GenericReply,		"AT+CGREG=1"		
,0x00,0x00,ID_ConfigureNetworkInfo	 },
 {ATGEN_GenericReply,		"AT+CREG=2"		,0x00,0x00,ID_ConfigureNetworkInfo	
 },
 {ATGEN_GenericReply,		"AT+CGREG=2"		
,0x00,0x00,ID_ConfigureNetworkInfo	 },
 {ATGEN_GenericReply,		"AT+COPS="		,0x00,0x00,ID_ConfigureNetworkInfo	
 },
