### ISSUE TITLE
Gammu-smsd 1.38.8 send long sms , but destination phone does not received sms

### ISSUE THREAD

**Issue by xiaomingwang1234** [gammu/wammu#20]
Hi,

recently,  I compile gammu 1.36.8 with window 7  and visual studio 201.

with gammu  I can send long sms. with gammu-smsd I can send , But my destination phone does not received

Clould you help me?
 
I use gammu-smsd-inject
 
C:\gammu>gammu-smsd-inject.exe -c smsdrc2.txt TEXT +5142919730 -len 400 -text "I
ni teks yang panjang. Ini teks yang panjang. Ini teks yang panjang. Ini teks yan
g panjang. Ini teks yang panjang. Ini teks yang panjang. Ini teks yang panjang.
Ini teks yang panjang. Ini teks yang panjang. Ini teks yang panjang."
 But My phone does not received sms
my smsd config file:
 
[gammu]
device = com31:
connection = at
[SMSD]
#runonreceive = /var/www/kalkun/scripts/daemon.sh
logfile = c:\Gammu\LOG.txt
commtimeout = 10
sendtimeout = 20
deliveryreport = log
phoneid = Key2
transmitformat = auto
DeliveryReport = log
service = sql
driver = ODBC
host = smsd
sql=MySQL

**Comment by nijel** [comment]
Any chance to get debug log? See http://wammu.eu/support/bugs/
