### ISSUE TITLE
Error when adding contact to Motorola Razr V3xx

### ISSUE THREAD

**Issue by mr-greenjeans** [gammu/wammu#24]
This may be the same as https://github.com/gammu/wammu/issues/23:

Using the latest git clone of gammu (1.37.3), python-gammu, and wammu (0.41), results in an unhandled exception when attempting to add a contact

[CODE]
Traceback:
  File "/usr/lib/python2.7/site-packages/Wammu/Main.py", line 1064, in NewContact
    self.EditContact({})
  File "/usr/lib/python2.7/site-packages/Wammu/Main.py", line 1175, in EditContact
    v = self.sm.GetMemory(v['MemoryType'], v['Location'])

Exception: ValueError: Missing key in dictionary: Location
[/CODE]

Here is the log file from a session in which I tried to add a contact:

[wammu-crash.txt](https://github.com/gammu/wammu/files/253553/wammu-crash.txt)

Remarks:

(1) I had previously used gammu 1.26 and wammu 0.30.1 from the Fedora 15 distribution with a Razr V3 without difficulty.  That version of gammu somehow corrupts text names when uploading them as contacts.  On the phone they display mainly as Chinese characters.

(2) After crashing, the current git versions have in fact uploaded to the phone, but again the contacts show as Chinese characters.

(3) The presumably unrelated error "GSM_GetBatteryCharge failed with error BUG[37]" is evidently a regression.  gammu 1.26/wammu 0.30.1 were able to retrieve battery charge from the phone.

(4) The current git versions of gammu/wammu are *extremely* slow at retrieving contacts from the v3xx.  Retrieving just one contact requires 3 to 5 minutes.

**Comment by nijel** [comment]
Indeed this is same as #23.
