### ISSUE TITLE
'setup.py build' fails on CentOS 6.7 / Python 2.6.6

### ISSUE THREAD

**Issue by tobiasvogel** [gammu/wammu#28]
On my SMS-gateway box 
[ **i686** , **CentOS 6.7** , Vanilla Distibution Version of **Python 2.6.6** ]
the **wammu 0.41** _setup.py_ script fails because of line _214_:

`tree.write(appdata, 'utf-8', True)`

with only the first two parameters, the setup.py script runs fine:

`tree.write(appdata, 'utf-8')`

I'm not very into Python at all, let alone the ElementTree module, so maybe this issue is very limited to older Python versions.

Nevertheless, reporting the bug hereby... 😉 
##

**Comment by nijel** [comment]
Okay, nobody really tested that in Python 2.6, that's quite old version :-). Unfortunately this is needed in Python 2.7, see 95fde5f9.
