### ISSUE TITLE
wammy failing to connect over bluetooth

### ISSUE THREAD

**Issue by hans-van-der-meyden** [gammu/wammu#30]
Running Fedora 23, with bluez ...39.
[wammu.txt](https://github.com/gammu/wammu/files/285390/wammu.txt)

Blueman works okay - suspect problem with obex driver.

Phone trying to connect to Galaxy GT-N7100

bluetootctl shows wammu connecting.

**Comment by nijel** [comment]
Try using blueat connection, the phone doesn't support irmc.

**Comment by hans-van-der-meyden** [comment]
--------------- System information ----------------
Platform     linux2
Python       2.7.11
wxPython     3.0.2.0
Wammu        0.40
python-gammu 2.5
Gammu        1.37.0
Bluetooth    PyBluez
locales      en_GB (UTF-8)
connection   blueat
device       BC:20:A4:30:D5:22
model        
Fri 2016/05/27 09:51:52: [Gammu            - 1.37.0]
Fri 2016/05/27 09:51:52: [Connection       - "blueat"]
Fri 2016/05/27 09:51:52: [Connection index - 0]
Fri 2016/05/27 09:51:52: [Model type       - ""]
Fri 2016/05/27 09:51:52: [Device           - "BC:20:A4:30:D5:22"]
Fri 2016/05/27 09:51:52: [Running on       - Linux, kernel 4.4.9-300.fc23.x86_64 (#1 SMP Wed May 4 23:56:27 UTC 2016)]
Fri 2016/05/27 09:51:52: Looking for suitable channel for AT
Fri 2016/05/27 09:51:52: Device BC:20:A4:30:D5:22 ("GT-N7100")
Fri 2016/05/27 09:51:55:    Channel 2 - "Headset Gateway" (score=0)
Fri 2016/05/27 09:51:55:    Channel 3 - "Handsfree Gateway" (score=0)
Fri 2016/05/27 09:51:55:    Channel 4 - "Sim Access Server" (score=0)
Fri 2016/05/27 09:51:55:    Channel 19 - "OBEX Phonebook Access Server" (score=0)
Fri 2016/05/27 09:51:55:    Channel 5 - "MAP SMS" (score=0)
Fri 2016/05/27 09:51:55:    Channel 12 - "OBEX Object Push" (score=0)
Fri 2016/05/27 09:51:55: No suitable bluetooth channel found!
Fri 2016/05/27 09:51:55: Init:GSM_TryGetModel failed with error NOTSUPPORTED[21]: Function not supported by phone.
Fri 2016/05/27 09:51:55: Entering GSM_SetIncomingSMS
Fri 2016/05/27 09:51:55: Entering GSM_SetIncomingCall
Fri 2016/05/27 09:51:55: Entering GSM_SetIncomingCB
Fri 2016/05/27 09:51:55: Entering GSM_SetIncomingUSSD

**Comment by nijel** [comment]
Okay I didn't realize it at beginning, but Android phones are not supported, see https://github.com/gammu/gammu/issues/81
