### ISSUE TITLE
Unhandled exception appeared

### ISSUE THREAD

**Issue by jrbsolucoes** [gammu/wammu#35]
Unhandled exception appeared. If you want to help improving this program, please report this together with description how this situation has happened. Please report in english, otherwise you will be most likely told to translate you report to english later.

Traceback:
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 983, in OnProgress
    del self.progress

Exception: AttributeError: progress

Debug log has been automatically saved to /tmp/wammu-crash-FtpVh8.log, you are strongly encouraged to include it in bugreport.

**Comment by nijel** [comment]
What Wammu version is that? Assuming that it's something older, this issue is already fixed since 3c3dd666345d855b0804291194dc13b7085d87b6. 

Please see http://wammu.eu/support/bugs/ for information how to submit useful bug reports.
