### ISSUE TITLE
Error al comunicar con el teléfono

### ISSUE THREAD

**Issue by ricardo-hernandez** [gammu/wammu#39]
El dispositivo «/dev/sdc» para comunicación con el teléfono no existe. Quizás no ha conectado el teléfono o la configuración es incorrecta.

Dispositivo Samsung GT-I8190L

**Comment by nijel** [comment]
`/dev/sdc` is definitely not a device to use with Gammu, it's USB storage.

Anyway Android phones are currently not supported, see https://github.com/gammu/gammu/issues/81
