### ISSUE TITLE
Wammu crash

### ISSUE THREAD

**Issue by Globlonux01** [gammu/wammu#42]
Trace :
  File "/usr/lib/python2.7/dist-packages/Wammu/Main.py", line 983, in OnProgress
    del self.progress

Exception : AttributeError: progress

[wammu-crash.txt](https://github.com/gammu/wammu/files/672317/wammu-crash.txt)

**Comment by nijel** [comment]
Already fixed in next version, see https://github.com/gammu/wammu/issues/25

**Comment by halim-kahraman** [comment]
Hello together, 

actually a new crash here.

On sending the sms to 8 user, wammu crashed

Log:
--------------- System information ----------------
Platform     win32
Python       2.7.14
wxPython     3.0.2.0
Wammu        0.44
python-gammu 2.11
Gammu        1.39.0
Bluetooth    PyBluez
locales      de_DE (cp1252)
connection   at19200
device       COM4
model        

------------------ Traceback ID -------------------
9876c0060e6cfae09acc81c59cfa55ab
-------------------- Traceback --------------------
  File "Wammu\Composer.pyo", line 665, in Okay
  File "wx\_windows.pyo", line 809, in EndModal
-------------------- Exception --------------------
PyAssertionError: C++ assertion "IsRunning()" failed at ..\..\src\common\evtloopcmn.cpp(83) in wxEventLoopBase::Exit(): Use ScheduleExit() on not running loop
---------------------------------------------------

![wammu-issue](https://user-images.githubusercontent.com/52968921/61310377-78ad6880-a7f4-11e9-9108-5a617102cec7.jpg)
