### ISSUE TITLE
Error in Windows (gammu.exe) when opening ports above 9?

### ISSUE THREAD

**Issue by wildfandango** [gammu/wammu#50]
Hi...

I have the following device in COM6:

Device: COM6
Manufacturer: Huawei
Model: unknown (E1762)
Firmware: 11.126.13.00.00

Configured as follows:
[Gammu]
Port = COM6
Connection = at

And it works perfectly, but if I change the COM port of MODEM in the device manager and I put any port above the COM 9 Gammu it returns the following message to me when trying to access the ...

Error opening device, it does not exist.

Maybe someting like...?
https://support.microsoft.com/en-us/help/115831/howto-specify-serial-ports-larger-than-com9

**Comment by nijel** [comment]
If I'm not misreading the code, it would work if you specify the port in lowercase, I'll fix this.
