### ISSUE TITLE
Unable to start the Wammu (APPCRASH)

### ISSUE THREAD

**Issue by asifahamedsi1** [gammu/wammu#55]
After selecting Phone Device if i click next it crashes, please help

Problem Event Name:	APPCRASH
  Application Name:	wammu.exe
  Application Version:	0.32.1.0
  Application Timestamp:	48554bd0
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7ba58
  Exception Code:	c0000005
  Exception Offset:	00038da9
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	1ec0
  Additional Information 2:	1ec0fd70d07d060e5bfcf53c69ad1739
  Additional Information 3:	3040
  Additional Information 4:	30403390ed20f1b32c61f314c386b874

**Comment by nijel** [comment]
Wammu build for Windows is quite old and that might be cause of these problems. Unfortunately there is no newer version available right now, see https://github.com/gammu/wammu/issues/51

**Comment by asifahamedsi1** [comment]
@nijel thank you for your quick reply.... Can you please suggest for which windows Wammu supports, I have tried with windows 7 and vista but same issue, will it work on xp? I have also tried to run wammu in xp SP2 compatibility mode on windows 7 but no luck.

**Comment by nijel** [comment]
I'm not really sure it will properly work anywhere. There were problems with Windows binaries, that's why we've stopped to provide them back then...

**Comment by asifahamedsi1** [comment]
Oh got it, I am also struggling to configure gammu in Ubuntu as its not identifying my Nokia 216 via USB or Bluetooth and details about supported phones are very old in gammu website not sure which recent phones model it supports, since I am very new to Linux I am stuck....

**Comment by nijel** [comment]
Let's deal with the Windows support at https://github.com/gammu/wammu/issues/51#issuecomment-346700066
