### ISSUE TITLE
Retrieve->Messages does not retrieve all messages

### ISSUE THREAD

**Issue by mauro3** [gammu/wammu#60]
Running `Retrieve->Messages` only fetches ~193~ 200 sms messages of the ~2500 I have on my Nokia phone.  Is there a setting to increase that number?

Running `gammu getallsms -pbk > sms.gammu` gets all 2500+ messages.

**Comment by mauro3** [comment]
The reason for the 200 messages is the line: https://github.com/gammu/wammu/blob/96c8992216e11442d92ade804ccc150089cc24d5/Wammu/Reader.py#L38.  Increasing that number retrieves more messages.  Thus setting the number to the number of SMS I get from running `gammu getallsms -pbk > sms.gammu` I can retrieve all my SMS.

But how could Wammu figure the number out by itself?  I have a Nokia 3720c.

**Comment by nijel** [comment]
I *think* I've fixed this. It would be great if you can test it as I don't have device which would behave this way.

**Comment by mauro3** [comment]
No, it doesn't work: when retrieving the progress bar increases until almost the end, then nothing happens anymore except "Estimated time" increases. Hitting "Cancel" does nothing except greying the "Cancel" button.

Take this with a grain of salt though as I just used Wammu 0.43 and replaced the Reader.py file with the one you made now.
