### ISSUE TITLE
Error opening device. Unknown, busy or no permissions

### ISSUE THREAD

**Issue by Maciej-Majcherek** [gammu/wammu#64]
Gammu version : 1.38.1
Wammu version : 0.43
python-gammu version : 2.7

~$ echo "All your base are belong to us" | gammu sendsms TEXT [my phone numb]
Error opening device. Unknown, busy or no permissions. 

Where do i need to change permissions ?

**Comment by nijel** [comment]
See our documentation: https://wammu.eu/docs/manual/config/#option-Device
