### ISSUE TITLE
unable to detect Fairphone 2 USB & Bluetooth

### ISSUE THREAD

**Issue by rv2931** [gammu/wammu#88]
Hello
I tried to use my fairphone 2 with Gammu
- USB : it seems that it doesn't detect at all my phone
- bluetooth : it says that "this functionnality is not supported by your phone"
Am I doing something wrong ?
Thank you in advance
[wammu.log](https://github.com/gammu/wammu/files/3963738/wammu.log)

**Comment by nijel** [comment]
see https://wammu.eu/docs/manual/faq/phone.html#are-android-phones-supported and https://github.com/gammu/gammu/issues/81
